
.MODEL SMALL
.STACK
.DATA

M1 DB 10,13,"MOUSE DRIVER PRESENT$"
.CODE

DISP MACRO XX
MOV AH,09
LEA DX,XX
INT 21H
ENDM

.STARTUP

MOV AX,0000 ;MOUSE DRIVER PRESENT OR NOT
INT 33H

; IF AX CONTAINS NON ZERO VALUE THEN MOUSE DRIVER PRESENT

CMP AX,00
JE LAST
DISP M1

MOV AX,0004H  ;MOUSE CURSOR POSITION
MOV CX,5 ;HORIZONTAL POSITION
MOV DX,5 ;VERTICAL POSITION
INT 33H

MOV AX,0007H ;SET HORIZONTAL LIMIT
MOV CX,0005H ;MIN X COORINATE
MOV DX,0010H ; MAX X COORINATE
INT 33H

MOV AX,0008H ;SET VERTICAL LIMIT
MOV CX,0005H ;MIN Y COORINATE
MOV DX,0010H ; MAX Y COORINATE
INT 33H

PIXEL:
MOV AX,0001 ;DISPLAY MOUSE - TEXT MODE - RECTANGULAR SHAPE CURSOR......GRAPHIC MODE -TRIANGULAR SHAPE CURSOR
INT 33H

MOV AX,0003; GET STATUS OF MOUSE BUTTON
INT 33H
; RESULT OF MOUSE STATUS IS RETURNED IN BX
CMP BX,01; LEFT BUTTON IS PRESSED
JE LEFT
JMP RIGHT ; RIGHT BUTTON CLICKED

LEFT:
MOV AX,0011H ; SETTING GRAPHICS MODE TO SHOW PIXEL ON LEFT CLICK
INT 10H
;MOV AX,0003
;INT 33H

MOV AH,0CH ;DISPLAY PIXEL IN GRAPHICS MODE
INT 10H

RIGHT:
;MOV AX,0001
;INT 33H

CMP BX,02
JE LAST
JMP PIXEL

LAST:
MOV AX,00 ;COMING BACK IN TEXT MODE
INT 10H

.EXIT 
END
